default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development: &development
  <<: *default
  database: pecunia_api_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
test:
  <<: *development
  database: pecunia_api_test
production:
  <<: *default
  database: pecunia_api_production
  username: pecunia_api
  password: <%= ENV["PECUNIA_API_DATABASE_PASSWORD"] %>
